
public class ExamString {
    public static void main(String[] args) {
        String cat = "Cat is a good pet";
        String dog = "Dog is loyal and friendly";
        String cow = "Cow is a kind one";
        String elephant = "Elephant is the cutest one in the animal world";
        String tiger = "Tiger is the national animal of India";
        String frog = "Frogs are the greatest parents in the animal world";
        String squirrel = "Squirrel is a forest farmer";
        String cheetah = "Cheetah is the fastest runner in the animal world";
        String deer = "The deer is a beautiful and gentle animal";
        String turtle = "Turtle is a long-liver";
        String honeybee = "Honeybees are hard workers";
        String giraffe = "Giraffe is a tall animal";
        String crab = "Crab has many legs";
        String pumpkin = "Pumpkin is a vegetable";
        String cucumber = "Cucumber is a vegetable";
        String ashgourd = "Ashgourd is a vegetable";
        String bittergourd = "Bittergourd is a vegetable";
        String moongbean = "Moongbean is a vegetable";
        String peanut = "Peanut is a nut";
        String rice = "Rice is a good carbohydrate";
        String ragi = "Ragi is a fiber-rich grain";
        String wheat = "Wheat is a grain";
        String jowar = "Jowar is a grain";
        String coconut = "Coconut is a nut";
        String snake = "Snake is a scary animal";
        String buffalo = "Buffalo is an innocent animal";
        String crow = "Crow is black in color";
        String parrot = "Parrot is green in color";
        String pigeon = "Pigeon is white in color";
        String kingfisher = "Kingfisher is sky blue in color";
        String peacock = "Peacock is the national bird of India";
        String banyan = "Banyan is the national tree of India";
        String anthem = "The national anthem of India is Jana Gana Mana";
        String fruit = "Mango is the national fruit of India";
        String flower = "Lotus is the national flower of India";
        String currency = "Rupee is the national currency of India";
        String vegetable = "Sweet pumpkin is the national vegetable of India";
        String game = "Hockey is the national game of India";
        String river = "Ganga is the national river of India";
        String flag = "The national flag of India is tricolor: saffron, white, and green";
        String heritageAnimal = "Elephant is the national heritage animal of India";
        String nationalAquaticAnimal = "The national aquatic animal of India is the dolphin";
        String reptile = "King cobra is the national reptile of India";
        String calendar = "The national calendar of India is Saka";
        String duck = "Duck sound: quack quack";
        String sparrow = "Sparrows have become rare because of our actions";
        String woodpecker = "Woodpecker works hard to find food";
        String owl = "Owl is a nocturnal animal";
        String hornbill = "Hornbills are inspirational couples";
        String flamingo = "Flamingos have attractive colors";
        String penguin = "Penguins are found in Antarctica";
        String eagle = "Eagles are aggressive birds";
        String hummingbird = "Hummingbirds are small and cute";
        String nightingale = "Nightingales are known for their singing";
        String strawberry = "Strawberry is a berry fruit";
        String peach = "Peach is a fruit";
        String date = "Date is a very sweet fruit";
        String pineapple = "Pineapple is a fruit";
        String jackfruit = "Jackfruit is a large fruit";
        String watermelon = "Watermelon is refreshing";
        String kiwi = "Kiwi is a fruit";
        String dragon = "Dragon fruit is a unique fruit";
        String onion = "Onion is a vegetable";
        String carrot = "Carrot is a vegetable";
        String cabbage = "Cabbage is a vegetable";
        String capsicum = "Capsicum is a vegetable";
        String tomato = "Tomato is a vegetable";
        String potato = "Potato is a vegetable";
        String peas = "Peas are vegetables";
        String brinjal = "Brinjal is a vegetable";
        String radish = "Radish is a vegetable";
        String beetroot = "Beetroot is a vegetable";
        String cashew = "Cashew is a nut";
        String almond = "Almond is a nut";
        String walnut = "Walnut is a nut";
        String raisin = "Raisin is a dry fruit";
        String fig = "Fig is a dry fruit";

        String pumpkinCucumber = pumpkin + " and " + cucumber;
        String ashgourdBitter = ashgourd + " and " + bittergourd;
        String moongbeanPeanut = moongbean + " and " + peanut;
        String riceRagi = rice + " and " + ragi;
        String wheatJowar = wheat + " and " + jowar;
        String onionCarrot = onion + " and " + carrot;
        String cabbageCapsicum = cabbage + " and " + capsicum;
        String tomatoPotato = tomato + " and " + potato;
        String peasBrinjal = peas + " and " + brinjal;
        String radishBeetroot = radish + " and " + beetroot;
        String strawberryPeach = strawberry + " and " + peach;
        String datePineapple = date + " and " + pineapple;
        String jackfruitWatermelon = jackfruit + " and " + watermelon;
        String kiwiDragon = kiwi + " and " + dragon;
        String coconutRaisin = coconut + " and " + raisin;
        String cashewRaisin = cashew + " and " + raisin;
        String almondRaisin = almond + " and " + raisin;
        String walnutFig = walnut + " and " + fig;
        String catDog = cat + " and " + dog;
        String cowElephant = cow + " and " + elephant;
        String tigerFrog = tiger + " and " + frog;
        String squirrelCheetah = squirrel + " and " + cheetah;
        String deerTurtle = deer + " and " + turtle;
        String honeybeeGiraffe = honeybee + " and " + giraffe;
        String crabSnake = crab + " and " + snake;
        String buffaloCrow = buffalo + " and " + crow;
        String parrotPigeon = parrot + " and " + pigeon;
        String kingfisherPeacock = kingfisher + " and " + peacock;
        String banyanAnthem = banyan + " and " + anthem;
        String fruitFlower = fruit + " and " + flower;
        String currencyVegetable = currency + " and " + vegetable;
        String gameRiver = game + " and " + river;
        String flagHeritageAnimal = flag + " and " + heritageAnimal;
        String nationalAquaticAnimalReptile = nationalAquaticAnimal + " and " + reptile;
        String calendarDuck = calendar + " and " + duck;
        String sparrowWoodpecker = sparrow + " and " + woodpecker;
        String owlHornbill = owl + " and " + hornbill;
        String flamingoPenguin = flamingo + " and " + penguin;
        String eagleHummingbird = eagle + " and " + hummingbird;
        String nightingaleStrawberry = nightingale + " and " + strawberry;
        String peachDate = peach + " and " + date;
        String pineappleJackfruit = pineapple + " and " + jackfruit;
        String watermelonKiwi = watermelon + " and " + kiwi;
        String dragonOnion = dragon + " and " + onion;
        String carrotCabbage = carrot + " and " + cabbage;
        String capsicumTomato = capsicum + " and " + tomato;
        String potatoPeas = potato + " and " + peas;
        String brinjalRadish = brinjal + " and " + radish;
        String beetrootCashew = beetroot + " and " + cashew;
        String almondWalnut = almond + " and " + walnut;
        String figCat = fig + " and " + cat;
        String dogCow = dog + " and " + cow;
        String elephantTiger = elephant + " and " + tiger;
        String frogSquirrel = frog + " and " + squirrel;
        String cheetahDeer = cheetah + " and " + deer;
        String turtleHoneybee = turtle + " and " + honeybee;
        String giraffeCrab = giraffe + " and " + crab;
        String snakeBuffalo = snake + " and " + buffalo;
        String crowParrot = crow + " and " + parrot;
        String pigeonKingfisher = pigeon + " and " + kingfisher;
        String peacockBanyan = peacock + " and " + banyan;
        String anthemFruit = anthem + " and " + fruit;
        String flowerCurrency = flower + " and " + currency;
        String vegetableGame = vegetable + " and " + game;

        System.out.println(pumpkinCucumber);
        System.out.println(ashgourdBitter);
        System.out.println(moongbeanPeanut);
        System.out.println(riceRagi);
        System.out.println(wheatJowar);
        System.out.println(onionCarrot);
        System.out.println(cabbageCapsicum);
        System.out.println(tomatoPotato);
        System.out.println(peasBrinjal);
        System.out.println(radishBeetroot);
        System.out.println(strawberryPeach);
        System.out.println(datePineapple);
        System.out.println(jackfruitWatermelon);
        System.out.println(kiwiDragon);
        System.out.println(coconutRaisin);
        System.out.println(cashewRaisin);
        System.out.println(almondRaisin);
        System.out.println(walnutFig);
        System.out.println(catDog);
        System.out.println(cowElephant);
        System.out.println(tigerFrog);
        System.out.println(squirrelCheetah);
        System.out.println(deerTurtle);
        System.out.println(honeybeeGiraffe);
        System.out.println(crabSnake);
        System.out.println(buffaloCrow);
        System.out.println(parrotPigeon);
        System.out.println(kingfisherPeacock);
        System.out.println(banyanAnthem);
        System.out.println(fruitFlower);
        System.out.println(currencyVegetable);
        System.out.println(gameRiver);
        System.out.println(flagHeritageAnimal);
        System.out.println(nationalAquaticAnimalReptile);
        System.out.println(calendarDuck);
        System.out.println(sparrowWoodpecker);
        System.out.println(owlHornbill);
        System.out.println(flamingoPenguin);
        System.out.println(eagleHummingbird);
        System.out.println(nightingaleStrawberry);
        System.out.println(peachDate);
        System.out.println(pineappleJackfruit);
        System.out.println(watermelonKiwi);
        System.out.println(dragonOnion);
        System.out.println(carrotCabbage);
        System.out.println(capsicumTomato);
        System.out.println(potatoPeas);
        System.out.println(brinjalRadish);
        System.out.println(beetrootCashew);
        System.out.println(almondWalnut);
        System.out.println(figCat);
        System.out.println(dogCow);
        System.out.println(elephantTiger);
        System.out.println(frogSquirrel);
        System.out.println(cheetahDeer);
        System.out.println(turtleHoneybee);
        System.out.println(giraffeCrab);
        System.out.println(snakeBuffalo);
        System.out.println(crowParrot);
        System.out.println(pigeonKingfisher);
        System.out.println(peacockBanyan);
        System.out.println(anthemFruit);
        System.out.println(flowerCurrency);
        System.out.println(vegetableGame);
    }
}
